import { Globe, Users } from 'lucide-react';

export default function CommunityExplore() {
  return (
    <div className="flex-1 overflow-y-auto p-8 bg-surface/30 hide-scrollbar">
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            Community Explore
          </h2>
          <p className="text-text-muted text-lg max-w-2xl mx-auto">
            Discover popular itineraries generated by other WanderMind travelers and clone them for your own adventure.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            { id: 1, title: '3 Days in Tokyo', author: 'Alex Chen', saves: 245, img: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26' },
            { id: 2, title: 'Weekend in Paris', author: 'Sarah J.', saves: 189, img: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a' },
            { id: 3, title: 'Bali Yoga Retreat', author: 'Mike T.', saves: 432, img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4' }
          ].map((trip) => (
            <div key={trip.id} className="glass-panel rounded-2xl overflow-hidden group cursor-pointer border border-white/5 hover:border-primary/30 transition-all duration-300">
              <div className="h-48 bg-gray-800 relative overflow-hidden">
                <img src={trip.img} alt={trip.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 opacity-80" />
                <div className="absolute inset-0 bg-gradient-to-t from-background to-transparent opacity-90"></div>
                <div className="absolute bottom-4 left-4 right-4 flex justify-between items-end">
                  <h3 className="font-bold text-lg text-white">{trip.title}</h3>
                  <div className="flex items-center gap-1 text-sm text-primary bg-primary/10 px-2 py-1 rounded-md backdrop-blur-md">
                    <Users size={14} /> {trip.saves}
                  </div>
                </div>
              </div>
              <div className="p-4 flex items-center gap-2 text-text-muted text-sm">
                <Globe size={16} /> Created by {trip.author}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
